### ISSUE TITLE
BitBucketConverter.py python3 error

### ISSUE THREAD

**Issue by alekob** [Portisch/RF-Bridge-EFM8BB1#166]
Hello,
running the latest version of BitBucketConverter.py on a Ubuntu 18.04 (Python 3.6.9) fails

Traceback (most recent call last):
  File "./BitBucketConverter.py", line 335, in <module>
    strInput = getInputStr()
  File "./BitBucketConverter.py", line 64, in getInputStr
    auxStr = raw_input("Enter B1 line: ")
NameError: name 'raw_input' is not defined

**Comment by pgScorpio** [comment]
Same here with Python 3.8.1 on Windows 10

Traceback (most recent call last):
  File "BitBucketConverter.py", line 335, in <module>
    strInput = getInputStr()
  File "BitBucketConverter.py", line 64, in getInputStr
    auxStr = raw_input("Enter B1 line: ")
NameError: name 'raw_input' is not defined

**Comment by MrRimmer** [comment]
I'm a complete python novice, but got it working by replacing raw_input() with input() - raw_input is deprecated in Python 3.
